In [3]:
import pandas as pd
import pickle
import numpy as np
from sklearn.ensemble import RandomForestRegressor

In [6]:
filename = './models/finalized_rf_model.sav'
loaded_model = pickle.load(open(filename, 'rb'))

In [18]:
df_norm = pd.read_csv('./all_normalized.csv')

In [19]:
df = pd.read_csv('./all_not_normalized.csv')

In [13]:
attributes = ['ageattest', 'resting_hr', 'height inch->cm',
           'resting_sbp', 'resting_dbp', 'weight Ib->kg']
df_norm[attributes]

ageattest  resting_hr  height inch->cm  resting_sbp  resting_dbp  \
0           42.0       60.00           186.70       122.00        82.00   
1           55.0       72.26           159.99       121.71        78.74   
2           62.0       72.26           157.00       121.71        78.74   
3           58.0       68.00           185.42       118.00        74.00   
4           55.0       72.26           171.90       121.71        78.74   
...          ...         ...              ...          ...          ...   
17320       47.0      110.00           179.07       124.00        74.00   
17321       26.0       96.00           165.10       108.00        72.00   
17322       50.0      106.00           181.61       118.00        72.00   
17323       20.0      105.00           182.88       122.00        76.00   
17324       75.0      111.00           170.18       138.00        94.00   

       weight Ib->kg  
0              84.81  
1              87.79  
2              78.09  
3              80.82  
4              76.93  
...              ...  
17320          80.28  
17321          79.37  
17322         115.20  
17323          71.21  
17324          65.77  

[17325 rows x 6 columns]

In [47]:
pred_y = loaded_model.predict(df_norm[attributes])
pred_y

array([170.16121621, 158.771047  , 163.60287548, ..., 184.1908143 ,
       195.36903027, 192.61375219])

In [28]:
real_y = np.array(df_norm['max_hr'])

In [31]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(real_y, pred_y))

9.785316259123542

In [34]:
df_norm[attributes].iloc[1]

ageattest          0.514706
resting_hr         0.457500
height inch->cm    0.254439
resting_sbp        0.379182
resting_dbp        0.484250
weight Ib->kg      0.291403
Name: 1, dtype: float64

In [33]:
loaded_model.predict([df_norm[attributes].iloc[1]])

array([158.771047])

In [46]:
params = np.array(df[attributes].iloc[1])
params

array([ 55.  ,  72.26, 159.99, 121.71,  78.74,  87.79])

In [43]:
maxs = np.array([88, 120, 208.28, 190, 120, 179.61])
mins = np.array([20, 32, 143.51, 80, 40, 50.03])

sub = maxs - mins
params = (params - mins) / sub
print(params)

[0.51470588 0.4575     0.25443878 0.37918182 0.48425    0.29140299]


In [44]:
loaded_model.predict([params])

array([158.771047])